
-- Add missing columns to eta_applications table to match the application form
ALTER TABLE public.eta_applications 
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS home_address TEXT,
ADD COLUMN IF NOT EXISTS occupation TEXT,
ADD COLUMN IF NOT EXISTS date_of_birth DATE,
ADD COLUMN IF NOT EXISTS place_of_birth TEXT,
ADD COLUMN IF NOT EXISTS passport_issue_date DATE,
ADD COLUMN IF NOT EXISTS passport_expiry_date DATE,
ADD COLUMN IF NOT EXISTS exit_date DATE,
ADD COLUMN IF NOT EXISTS purpose_of_visit TEXT,
ADD COLUMN IF NOT EXISTS accommodation_address TEXT,
ADD COLUMN IF NOT EXISTS selfie_url TEXT,
ADD COLUMN IF NOT EXISTS arrival_mode TEXT DEFAULT 'air',
ADD COLUMN IF NOT EXISTS departure_mode TEXT DEFAULT 'air',
ADD COLUMN IF NOT EXISTS arrival_port TEXT,
ADD COLUMN IF NOT EXISTS departure_port TEXT,
ADD COLUMN IF NOT EXISTS arrival_airline TEXT,
ADD COLUMN IF NOT EXISTS departure_airline TEXT,
ADD COLUMN IF NOT EXISTS flight_number TEXT,
ADD COLUMN IF NOT EXISTS departure_flight_number TEXT,
ADD COLUMN IF NOT EXISTS final_destination_country TEXT,
ADD COLUMN IF NOT EXISTS accommodation_check_in_date DATE,
ADD COLUMN IF NOT EXISTS accommodation_check_out_date DATE,
ADD COLUMN IF NOT EXISTS trip_financed_by_third_party BOOLEAN,
ADD COLUMN IF NOT EXISTS country_of_birth TEXT,
ADD COLUMN IF NOT EXISTS nationality_at_birth TEXT,
ADD COLUMN IF NOT EXISTS convicted_in_past_5_years BOOLEAN,
ADD COLUMN IF NOT EXISTS denied_entry_to_kenya BOOLEAN,
ADD COLUMN IF NOT EXISTS marital_status TEXT,
ADD COLUMN IF NOT EXISTS previously_travelled_to_kenya BOOLEAN,
ADD COLUMN IF NOT EXISTS customs_declaration BOOLEAN,
ADD COLUMN IF NOT EXISTS bringing_currency_over_5000 BOOLEAN;
